version: '3.9'

services:
  local-db:
    image: mysql:8.0.28-oracle
    container_name: samithiwat-role-db
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
